name: macOS
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Setting the Environment Up.
      env:
        MAC_USER_PASSWORD: ${{ secrets.MAC_USER_PASSWORD }}
      run: source setup.sh "$MAC_USER_PASSWORD"
    - name: ngrok is now listening...
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: Setup Session
      uses: mxschmitt/action-tmate@v3
